### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by NSAntoine** [evelyneee/discord.swift#3]
List of things yet to do:

- [ ] Add slash command support
- [ ] Properly handle gateway stuff
- [ ] Make Discord Types conform to CustomStringConvertible
- [x] Add Support for more Discord types like Invite, Sticker, etc
- [x] Add functions like `fetchMessages`, `deleteChannel`, etc etc
